sonar.projectKey=travel-app
sonar.projectName=Travel Inter-Urban SaaS
sonar.projectVersion=1.0.0
sonar.host.url=http://localhost:9000

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.java.libraries=target/dependency/*.jar

sonar.sourceEncoding=UTF-8
sonar.java.source=21

# Couverture
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusions
sonar.exclusions=\
  **/entity/**,\
  **/enums/**,\
  **/dto/**,\
  **/config/**,\
  **/TravelApplication.java,\
  **/seed/DataSeeder.java

sonar.coverage.exclusions=\
  **/entity/**,\
  **/enums/**,\
  **/dto/**,\
  **/config/**,\
  **/exception/**,\
  **/seed/**,\
  **/TravelApplication.java

sonar.cpd.exclusions=\
  **/entity/**,\
  **/dto/**

# Quality Gate
sonar.qualitygate.wait=true